int segment[] = {2,3,4,5,6,7,8,9,10,11,12,13};
#define twelve 22
#define thirteen 24
void setup() {
  for(int i =0; i<13; i++){
    pinMode(segment[i],OUTPUT);
    pinMode(twelve,OUTPUT);
    pinMode(thirteen,OUTPUT);
  }

}

void loop() {
  //0-10
  digitalWrite(segment[0],0);
  digitalWrite(segment[1],0);
  digitalWrite(segment[2],0);
  digitalWrite(segment[3],0);
  digitalWrite(segment[4],0);
  digitalWrite(segment[5],1);
  digitalWrite(segment[6],0);
  // 0
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],0);
  digitalWrite(twelve,1);
  digitalWrite(thirteen,0);
  delay(1000); 
  // 1
  digitalWrite(segment[7],1);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],1);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,1);
  digitalWrite(thirteen,1);
  delay(1000);
  //2 
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],1);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],0);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,1);
  delay(1000);
  //3
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,1);
  delay(1000); 
  //4
  digitalWrite(segment[7],1);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],1);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000);
  //5
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],1);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000);
  //6
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],1);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],0);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000); 
  //7
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],1);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,1);
  digitalWrite(thirteen,1);
  delay(1000);
  //8 
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],0);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000);
  //9 
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000);
  //10-19
  digitalWrite(segment[0],1);
  digitalWrite(segment[1],0);
  digitalWrite(segment[2],0);
  digitalWrite(segment[3],1);
  digitalWrite(segment[4],1);
  digitalWrite(segment[5],1);
  digitalWrite(segment[6],1);
  //10
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],0);
  digitalWrite(twelve,1);
  digitalWrite(thirteen,0);
  delay(1000); 
  //11
  digitalWrite(segment[7],1);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],1);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,1);
  digitalWrite(thirteen,1);
  delay(1000);
  //12 
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],1);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],0);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,1);
  delay(1000);
  //13
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,1);
  delay(1000); 
  //14
  digitalWrite(segment[7],1);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],1);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000);
  //15
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],1);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000);
  //16
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],1);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],0);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000); 
  //17
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],1);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,1);
  digitalWrite(thirteen,1);
  delay(1000);
  //18 
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],0);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000);
  //19 
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000);
  //20-29
  digitalWrite(segment[0],0);
  digitalWrite(segment[1],0);
  digitalWrite(segment[2],1);
  digitalWrite(segment[3],0);
  digitalWrite(segment[4],0);
  digitalWrite(segment[5],0);
  digitalWrite(segment[6],1);
  //20
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],0);
  digitalWrite(twelve,1);
  digitalWrite(thirteen,0);
  delay(1000); 
  //21
  digitalWrite(segment[7],1);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],1);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,1);
  digitalWrite(thirteen,1);
  delay(1000);
  //22 
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],1);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],0);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,1);
  delay(1000);
  //23
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,1);
  delay(1000); 
  //24
  digitalWrite(segment[7],1);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],1);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000);
  //25
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],1);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000);
  //26
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],1);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],0);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000); 
  //27
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],1);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,1);
  digitalWrite(thirteen,1);
  delay(1000);
  //28 
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],0);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000);
  //29 
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000);       
  //30-39
  digitalWrite(segment[0],0);
  digitalWrite(segment[1],0);
  digitalWrite(segment[2],0);
  digitalWrite(segment[3],0);
  digitalWrite(segment[4],1);
  digitalWrite(segment[5],0);
  digitalWrite(segment[6],1);
  //30
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],0);
  digitalWrite(twelve,1);
  digitalWrite(thirteen,0);
  delay(1000); 
  //31
  digitalWrite(segment[7],1);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],1);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,1);
  digitalWrite(thirteen,1);
  delay(1000);
  //32 
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],1);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],0);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,1);
  delay(1000);
  //33
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,1);
  delay(1000); 
  //34
  digitalWrite(segment[7],1);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],1);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000);
  //35
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],1);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000);
  //36
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],1);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],0);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000); 
  //37
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],1);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,1);
  digitalWrite(thirteen,1);
  delay(1000);
  //38 
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],0);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000);
  //39 
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000); 
  //40-49
  digitalWrite(segment[0],1);
  digitalWrite(segment[1],0);
  digitalWrite(segment[2],0);
  digitalWrite(segment[3],1);
  digitalWrite(segment[4],1);
  digitalWrite(segment[5],0);
  digitalWrite(segment[6],0);
  //40
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],0);
  digitalWrite(twelve,1);
  digitalWrite(thirteen,0);
  delay(1000); 
  //41
  digitalWrite(segment[7],1);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],1);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,1);
  digitalWrite(thirteen,1);
  delay(1000);
  //42 
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],1);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],0);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,1);
  delay(1000);
  //43
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,1);
  delay(1000); 
  //44
  digitalWrite(segment[7],1);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],1);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000);
  //45
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],1);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000);
  //46
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],1);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],0);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000); 
  //47
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],1);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,1);
  digitalWrite(thirteen,1);
  delay(1000);
  //48 
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],0);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000);
  //49 
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000);
  //50-59
  digitalWrite(segment[0],0);
  digitalWrite(segment[1],1);
  digitalWrite(segment[2],0);
  digitalWrite(segment[3],0);
  digitalWrite(segment[4],1);
  digitalWrite(segment[5],0);
  digitalWrite(segment[6],0);
  //50
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],0);
  digitalWrite(twelve,1);
  digitalWrite(thirteen,0);
  delay(1000); 
  //51
  digitalWrite(segment[7],1);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],1);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,1);
  digitalWrite(thirteen,1);
  delay(1000);
  //52 
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],1);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],0);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,1);
  delay(1000);
  //53
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,1);
  delay(1000); 
  //54
  digitalWrite(segment[7],1);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],1);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000);
  //55
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],1);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000);
  //56
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],1);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],0);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000); 
  //57
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],1);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,1);
  digitalWrite(thirteen,1);
  delay(1000);
  //58 
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],0);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000);
  //59 
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000); 
  //60-69
  digitalWrite(segment[0],0);
  digitalWrite(segment[1],1);
  digitalWrite(segment[2],0);
  digitalWrite(segment[3],0);
  digitalWrite(segment[4],0);
  digitalWrite(segment[5],0);
  digitalWrite(segment[6],0);
  //60
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],0);
  digitalWrite(twelve,1);
  digitalWrite(thirteen,0);
  delay(1000); 
  //61
  digitalWrite(segment[7],1);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],1);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,1);
  digitalWrite(thirteen,1);
  delay(1000);
  //62 
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],1);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],0);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,1);
  delay(1000);
  //63
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,1);
  delay(1000); 
  //64
  digitalWrite(segment[7],1);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],1);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000);
  //65
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],1);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000);
  //66
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],1);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],0);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000); 
  //67
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],1);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,1);
  digitalWrite(thirteen,1);
  delay(1000);
  //68 
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],0);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000);
  //69 
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000); 
  //70-79
  digitalWrite(segment[0],0);
  digitalWrite(segment[1],0);
  digitalWrite(segment[2],0);
  digitalWrite(segment[3],1);
  digitalWrite(segment[4],1);
  digitalWrite(segment[5],1);
  digitalWrite(segment[6],1);
  //70
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],0);
  digitalWrite(twelve,1);
  digitalWrite(thirteen,0);
  delay(1000); 
  //71
  digitalWrite(segment[7],1);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],1);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,1);
  digitalWrite(thirteen,1);
  delay(1000);
  //72 
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],1);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],0);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,1);
  delay(1000);
  //73
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,1);
  delay(1000); 
  //74
  digitalWrite(segment[7],1);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],1);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000);
  //75
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],1);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000);
  //76
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],1);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],0);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000); 
  //77
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],1);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,1);
  digitalWrite(thirteen,1);
  delay(1000);
  //78 
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],0);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000);
  //79 
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000); 
  //80-89
  digitalWrite(segment[0],0);
  digitalWrite(segment[1],0);
  digitalWrite(segment[2],0);
  digitalWrite(segment[3],0);
  digitalWrite(segment[4],0);
  digitalWrite(segment[5],0);
  digitalWrite(segment[6],0);
  //80
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],0);
  digitalWrite(twelve,1);
  digitalWrite(thirteen,0);
  delay(1000); 
  //81
  digitalWrite(segment[7],1);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],1);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,1);
  digitalWrite(thirteen,1);
  delay(1000);
  //82 
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],1);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],0);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,1);
  delay(1000);
  //83
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,1);
  delay(1000); 
  //84
  digitalWrite(segment[7],1);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],1);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000);
  //85
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],1);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000);
  //86
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],1);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],0);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000); 
  //87
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],1);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,1);
  digitalWrite(thirteen,1);
  delay(1000);
  //88 
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],0);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000);
  //89 
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000);
  //90-99
  digitalWrite(segment[0],0);
  digitalWrite(segment[1],0);
  digitalWrite(segment[2],0);
  digitalWrite(segment[3],0);
  digitalWrite(segment[4],1);
  digitalWrite(segment[5],0);
  digitalWrite(segment[6],0);
  //90
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],0);
  digitalWrite(twelve,1);
  digitalWrite(thirteen,0);
  delay(1000); 
  //91
  digitalWrite(segment[7],1);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],1);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,1);
  digitalWrite(thirteen,1);
  delay(1000);
  //92 
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],1);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],0);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,1);
  delay(1000);
  //93
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,1);
  delay(1000); 
  //94
  digitalWrite(segment[7],1);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],1);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000);
  //95
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],1);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000);
  //96
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],1);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],0);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000); 
  //97
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],1);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,1);
  digitalWrite(thirteen,1);
  delay(1000);
  //98 
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],0);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000);
  //99 
  digitalWrite(segment[7],0);
  digitalWrite(segment[8],0);
  digitalWrite(segment[9],0);
  digitalWrite(segment[10],0);
  digitalWrite(segment[11],1);
  digitalWrite(twelve,0);
  digitalWrite(thirteen,0);
  delay(1000);

}
